# -*- coding: utf-8 -*-
"""basics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PvhXQ3xGzMUeahbbrGwkhwGeHCMa1s0V
"""

# => For Basics of Python:

a = 3
b = 2

# Arithmetic Operators
print("Arithmetic Operators:")
print(a + b)       # Addition
print(a - b)       # Subtraction
print(a * b)       # Multiplication
print(a / b)       # Division
print(a % b)       # Modulus
print(a ** b)      # Exponentiation
print(" ")

# Comparison Operators
print("Comparison Operators:")
print(a == b)      # Equal
print(a != b)      # Not Equal
print(a > b)       # Greater than
print(a < b)       # Less than
print(a >= b)      # Greater than or equal to
print(a <= b)      # Less than or equal to
print(" ")

# Assignment Operators
print("Assignment Operators:")
c = a + b
print(c)

c += a
print(c)

c -= a
print(c)

c *= a
print(c)

c /= a
print(c)

c %= a
print(c)
print(" ")

# Bitwise Operators
a = 60
b = 13

print("Bitwise Operators:")
print(a & b)       # AND
print(a | b)       # OR
print(a ^ b)       # XOR
print(~a)          # NOT
print(a << 2)      # Left Shift
print(a >> 2)      # Right Shift
print(" ")

# Logical Operators
print("Logical Operators:")
print(True and False)
print(True or False)
print(not (True and False))
print(" ")

# Membership Operators
y = [10, 20, 30]
x = 15

print("Membership Operators:")
print(x in y)
print(x not in y)
print(" ")

# Identity Operators
n1 = 5
n2 = 10

print("Identity Operators:")
print(n1 is n2)
print(n1 is not n2)
print(" ")

# Decision Making

# if statement
age = 19
print("If Statement:")
if age >= 18:
    print("You can vote")
print(" ")

# if-else statement
num = 12
print("If-Else Statement:")
if num % 2 == 0:
    print("Number is even")
else:
    print("Number is odd")
print(" ")

# if-elif-else ladder
n = 0
print("If-Elif-Else Ladder:")
if n > 0:
    print("Number is positive")
elif n < 0:
    print("Number is negative")
else:
    print("Number is zero")
print(" ")

# While loop
print("While Loop:")
num = 1
while num <= 10:
    print("Number is", num)
    num = num + 1
print(" ")

# For loop
print("For Loop:")
fruits = ["apple", "banana", "mango", "orange"]
for fruit in fruits:
    print(fruit)
print(" ")

# Function
print("Function Example:")
def greet():
    print("Hello, How are You?")

greet()
print(" ")

# Function with arguments
print("Function with Arguments:")

def sum(num1, num2):
    add = num1 + num2
    print("Sum is", add)

sum(3, 2)
print(" ")

# Break Statement
print("Break Statement:")
value = range(5)
for x in value:
    if x == 3:
        break
    print("x is", x)
print(" ")

# Continue Statement
print("Continue Statement:")
for x in value:
    if x == 3:
        continue
    print("x is", x)
print(" ")

# Mathematical Functions
print("Mathematical Functions:")

a = 3
b = 2

r = max(a, b)
print("Maximum is:", r)

r = min(a, b)
print("Minimum is:", r)
print(" ")

# String Methods
print("String Methods:")

str = "shubham"

print(str.capitalize())   # Capitalize first letter
print(str.isalnum())      # True if all characters are alphanumeric
print(str.isalpha())      # True if all characters are alphabetic
print(str.isdigit())      # False because it contains letters
print(str.islower())      # True because all are lowercase
print(str.isspace())      # False because it's not only spaces
print(str.isupper())      # False because all are lowercase
print(len(str))           # Length of the string

print(str.lower())        # Convert to lowercase
print(max(str))           # Highest ASCII character
print(min(str))           # Lowest ASCII character
print(str.upper())        # Convert to uppercase
print(" ")

# Basic List Operations
print("Basic List Operations:")
print([1, 2, 3] + [4, 5, 6])      # List concatenation
print(['Hi'] * 3)                 # List repetition
print(3 in [1, 2, 3])             # Membership check
print(" ")

# List Update
print("List Update:")
list = ["shubham", "shivam", "deep"]
print("Original list:", list)

list[1] = "samarth"               # Update single element
print("After changing index 1:", list)

list[1:3] = ["sahil", "dhaval"]   # Update a slice of list
print("After slicing 1 to 3:", list)
print(" ")